package grammaticalframework.absyn; // Java Package generated by the BNF Converter.

public class IntLiteral extends Lit {
    public final int integer_;

    public IntLiteral(int p1) {
        integer_ = p1;
    }

    public <R, A> R accept(grammaticalframework.absyn.Lit.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof grammaticalframework.absyn.IntLiteral) {
            grammaticalframework.absyn.IntLiteral x = (grammaticalframework.absyn.IntLiteral) o;
            return this.integer_ == x.integer_;
        }
        return false;
    }

    public int hashCode() {
        return this.integer_;
    }


}
