package grammaticalframework.absyn; // Java Package generated by the BNF Converter.

public class Literal implements AbsynTree {
    public final Lit lit_;

    public Literal(Lit p1) {
        lit_ = p1;
    }

    public <R, A> R accept(Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof grammaticalframework.absyn.Literal) {
            grammaticalframework.absyn.Literal x = (grammaticalframework.absyn.Literal) o;
            return this.lit_.equals(x.lit_);
        }
        return false;
    }

    public int hashCode() {
        return this.lit_.hashCode();
    }


}
