package grammaticalframework.Trees.absyn; // Java Package generated by the BNF Converter.

public abstract class AbsynTree implements java.io.Serializable {
    public abstract <R, A> R accept(AbsynTree.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(grammaticalframework.Trees.absyn.Lambda p, A arg);

        public R visit(grammaticalframework.Trees.absyn.Variable p, A arg);

        public R visit(grammaticalframework.Trees.absyn.Application p, A arg);

        public R visit(grammaticalframework.Trees.absyn.Literal p, A arg);

        public R visit(grammaticalframework.Trees.absyn.MetaVariable p, A arg);

        public R visit(grammaticalframework.Trees.absyn.Function p, A arg);

    }

}
