package grammaticalframework.Trees.absyn; // Java Package generated by the BNF Converter.

public class IntLiteral extends Lit {
  public final Integer integer_;

  public IntLiteral(Integer p1) { integer_ = p1; }

  public <R,A> R accept(grammaticalframework.Trees.absyn.Lit.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammaticalframework.Trees.absyn.IntLiteral) {
      grammaticalframework.Trees.absyn.IntLiteral x = (grammaticalframework.Trees.absyn.IntLiteral)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
