package grammaticalframework.Trees.absyn; // Java Package generated by the BNF Converter.

public abstract class Lit implements java.io.Serializable {
  public abstract <R,A> R accept(Lit.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammaticalframework.Trees.absyn.IntLiteral p, A arg);
    public R visit(grammaticalframework.Trees.absyn.FloatLiteral p, A arg);
    public R visit(grammaticalframework.Trees.absyn.StringLiteral p, A arg);

  }

}
