package grammaticalframework.Trees.absyn; // Java Package generated by the BNF Converter.

public class Literal extends AbsynTree {
  public final Lit lit_;

  public Literal(Lit p1) { lit_ = p1; }

  public <R,A> R accept(AbsynTree.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammaticalframework.Trees.absyn.Literal) {
      grammaticalframework.Trees.absyn.Literal x = (grammaticalframework.Trees.absyn.Literal)o;
      return this.lit_.equals(x.lit_);
    }
    return false;
  }

  public int hashCode() {
    return this.lit_.hashCode();
  }


}
