package grammaticalframework.Trees.absyn; // Java Package generated by the BNF Converter.

public class MetaVariable extends AbsynTree {
  public final Integer integer_;

  public MetaVariable(Integer p1) { integer_ = p1; }

  public <R,A> R accept(AbsynTree.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammaticalframework.Trees.absyn.MetaVariable) {
      grammaticalframework.Trees.absyn.MetaVariable x = (grammaticalframework.Trees.absyn.MetaVariable)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
